name: Build & Deploy Digest

on:
  schedule:
    # 02:00 UTC  ≈ 06:00 UAE every day
    - cron:  '0 2 * * *'
  workflow_dispatch:        # manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser python-dateutil

      - name: Run scraper → generate index.html
        env:
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}   # still available if script uses it locally
        run: |
          python dubai_news_scraper.py

      - name: Commit & push if index.html changed
        run: |
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html                # only index.html
          git diff --cached --quiet && echo "No page changes" || git commit -m "Auto-update digest"
          git push
